#!/bin/bash
DNS_SERVER=cs5700cdnproject.ccs.neu.edu
CDN_SERVERS=('ec2-54-159-99-25.compute-1.amazonaws.com'
  'ec2-50-18-189-64.us-west-1.compute.amazonaws.com'
  'ec2-18-229-54-5.sa-east-1.compute.amazonaws.com'
  'ec2-13-244-183-11.af-south-1.compute.amazonaws.com'
  'ec2-13-36-115-83.eu-west-3.compute.amazonaws.com'
  'ec2-13-51-89-160.eu-north-1.compute.amazonaws.com'
  'ec2-65-1-183-44.ap-south-1.compute.amazonaws.com'
  'ec2-13-208-85-51.ap-northeast-3.compute.amazonaws.com'
  'ec2-54-79-190-216.ap-southeast-2.compute.amazonaws.com')
DNS_SERVER_DIR=team-w-dns
HTTP_SERVER_DIR=team-w-http
PORT=40001
NAME=cs5700cdn.example.com
ORIGIN=cs5700cdnorigin.ccs.neu.edu
USERNAME=''
KEYFILE=''

while getopts ":p:o:n:u:i:" opt; do
  case ${opt} in
  p)
    PORT=${OPTARG}
    ;;
  o)
    ORIGIN=${OPTARG}
    ;;
  n)
    NAME=${OPTARG}
    ;;
  u)
    USERNAME=${OPTARG}
    ;;
  i)
    KEYFILE=${OPTARG}
    ;;
  \?)
    echo "usage: ./runCDN -p <port> -o <origin> -n <name> -u <username> -i <keyfile>"
    ;;
  esac
done
# debugging argument parsing
function print_args() {
  echo "port: $PORT, origin: $ORIGIN, name: $NAME, username: $USERNAME, keyfile: $KEYFILE"
}

print_args

# deploy dns server
echo "Starting DNS server on $DNS_SERVER..."
ssh -i $KEYFILE $USERNAME@$DNS_SERVER "cd ~/$DNS_SERVER_DIR; ./dnsserver -p $PORT -n $NAME > /tmp/team-w-dns.log 2>&1 &"
echo "DNS server running on $DNS_SERVER..."


# deploy http server
for cdn_host in "${CDN_SERVERS[@]}";
do
  echo "Starting HTTP server on $cdn_host..."
  ssh -i $KEYFILE $USERNAME@$cdn_host "cd ~/$HTTP_SERVER_DIR; /usr/lib/memmanaged/python3 httpserver -p $PORT -o $ORIGIN > /tmp/team-w-http.log 2>&1 &"
  echo "HTTP server started on $cdn_host..."
done